site_name: Especialização em Visão Computacional
theme:
  name: material # or other theme
  palette:
    primary: blue
  language: pt-BR

repo_name: "carlosfab/visao-computacional"
repo_url: "https://github.com/carlosfab/visao-computacional"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
