# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/visao-computacional',
                'doc_host': 'https://carlosfab.github.io',
                'git_url': 'https://github.com/carlosfab/visao-computacional',
                'lib_path': 'visao_computacional'},
  'syms': {'visao_computacional.core': {'visao_computacional.core.foo': ('core.html#foo', 'visao_computacional/core.py')}}}
